### ISSUE TITLE
Getting token with POST, not GET

### ISSUE THREAD

**Issue by tutnes** [vippsas/bankid-statuspage-api#1]
Shouldn't this be POST and not GET?

HTTP Method | Production URL
-- | --
GET | https://oidc.bankidapis.no/auth/realms/prod/protocol/openid-connect/token

**Comment by devbeard** [comment]
Adding my +1 to this instead of registering a new issue. When calling the endpoint with GET it fails with error message 

```
{
    "error": "RESTEASY****reacted***: No resource method found for GET, return 405 with Allow header"
}
```

Documentation should say `POST`

**Comment by garmannslund** [comment]
Thank you for reporting the issue.
The issue has been resolved in https://github.com/vippsas/bankid-statuspage-api/commit/93c134cb3e276e7102418467e3fcaaf72f999192.
